"""add voice_profile_id to projects

Revision ID: b1ec7329c18f
Revises: dbc43864a037
Create Date: 2026-05-11 02:06:52.409309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ec7329c18f'
down_revision: Union[str, Sequence[str], None] = 'dbc43864a037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('voice_profile_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'voice_profile_id')
    # ### end Alembic commands ###
